// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGunXoLyXeI6MAkBD5e_nI5lBr3flWTg',
    appId: '1:895293275487:web:82773e9ca885019787caea',
    messagingSenderId: '895293275487',
    projectId: 'shebapathway',
    authDomain: 'shebapathway.firebaseapp.com',
    storageBucket: 'shebapathway.firebasestorage.app',
    measurementId: 'G-97S2C1WG6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu-D9Ulvfin9klDLBqu9bKK0JkibfsV8E',
    appId: '1:895293275487:android:f719d2150b9a178387caea',
    messagingSenderId: '895293275487',
    projectId: 'shebapathway',
    storageBucket: 'shebapathway.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvaDfHBPEDs6SXS6vsi5eMHAgIRcyi5tk',
    appId: '1:895293275487:ios:a14abe241a62901687caea',
    messagingSenderId: '895293275487',
    projectId: 'shebapathway',
    storageBucket: 'shebapathway.firebasestorage.app',
    iosBundleId: 'com.example.shebaPathway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvaDfHBPEDs6SXS6vsi5eMHAgIRcyi5tk',
    appId: '1:895293275487:ios:a14abe241a62901687caea',
    messagingSenderId: '895293275487',
    projectId: 'shebapathway',
    storageBucket: 'shebapathway.firebasestorage.app',
    iosBundleId: 'com.example.shebaPathway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjGunXoLyXeI6MAkBD5e_nI5lBr3flWTg',
    appId: '1:895293275487:web:2ccde38618d0e75287caea',
    messagingSenderId: '895293275487',
    projectId: 'shebapathway',
    authDomain: 'shebapathway.firebaseapp.com',
    storageBucket: 'shebapathway.firebasestorage.app',
    measurementId: 'G-NT7YJDYCYK',
  );
}
